### ISSUE TITLE
🛑 Matrix - Synapse is down

### ISSUE THREAD

**Issue by damn-b0t** [DaMnGoodIT/upptime#37]
In [`28cf1f5`](https://github.com/DaMnGoodIT/upptime/commit/28cf1f5d988d536135f701072cdfa32f01750ba2
), Matrix - Synapse (https://matrix.b0t.at/health) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by a-mnich** [comment]
false alarm
